In [1]:
import torch 

In [2]:
data = torch.load('/data1/saaket/lsd_data/data/processed/conventional/best_bbox_arr_train_augmented_one_utterance_all_floors.pt')

In [2]:
data2 = torch.load('/data1/saaket/lsd_data/data/processed/conventional/best_bbox_arr_train_one_utterance_all_floors.pt')

In [4]:
data2[2]['floors']

{0: [(0,
   'I am on a landing of a staircase. In the room is a pool table and fireplace with a high back pink chair near the fireplace.',
   array([374, 318, 454, 463], dtype=int32)),
  (2,
   "No. It's a billiard/pool table on the rug. There is a large plant next to the door. I'm on the landing of the staircase.",
   array([584, 306, 739, 379], dtype=int32))],
 2: [(1,
   "It's a pool table. Under the pool table is a floral/patterned rug. There is also a white couch on the other side of the room under a window.",
   array([527, 264, 751, 387], dtype=int32))]}

In [16]:
data[2]['floors']

{0: [(0,
   'I am on a landing of a staircase. In the room is a pool table and fireplace with a high back pink chair near the fireplace.',
   array([374, 318, 454, 463], dtype=int32))]}

In [13]:
data2[0]['floors']

{1: [(0,
   'Look for a white couch next to a rug with square patterns that are blue black and white.',
   array([495, 351, 557, 426], dtype=int32))],
 0: [(1,
   'Put me in the middle of the rug.',
   array([538, 286, 658, 411], dtype=int32))]}